- name: Create the database's
  mysql_db: name={{ db.name }} state=present

- name: Create the database users
  mysql_user: name={{ db.user_name|default(db.name) }}  password={{ db.user_pass|default(db.name) }}
                priv={{ db.priv|default(db.name+".*:ALL") }} state=present host={{ db.host | default("localhost") }}