- name: Add key for dotdeb repo
  action: apt_key url='http://www.dotdeb.org/dotdeb.gpg' state=present

- name: Add dotdeb repo for php 5.5
  action: apt_repository repo='deb http://packages.dotdeb.org wheezy-php55 all' state=present update_cache=yes

- name: install php-fpm
  action: apt name=php5-fpm state=installed

- name: php install needed modules
  action: apt name={{ item }} state=present
  with_items:
        - php5-cli
        - php5-common
        - php5-curl
        - php5-gd
        - php5-mysql
        - php5-pgsql
        - php5-mcrypt
        - php5-xdebug
        - php5-apcu
        - php5-intl

- name: Set php5-fpm timezone
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='^;?date.timezone\s*='
              line="date.timezone = '{{ timezone }}'"
              state=present
  notify:
    - restart php5-fpm

- name: Set php5 cli timezone
  lineinfile: dest=/etc/php5/cli/php.ini
                  regexp='^;?date.timezone\s*='
                  line="date.timezone = '{{ timezone }}'"
                  state=present

- name: Increase PHP maximum function nesting level
  lineinfile: dest=/etc/php5/mods-available/xdebug.ini
                  insertafter=EOF
                  regexp='^;?xdebug.max_nesting_level\s*='
                  line="xdebug.max_nesting_level=300"
                  state=present

- name: service run php5-fpm
  action: service name=php5-fpm state=started
