- name: install zsh
  apt: pkg=zsh state=latest

- name: create etc/zsh
  file: name=/etc/zsh state=directory owner=root group=root

- name: copy configuration files
  copy: src={{ item }} dest=/{{ item }} owner=root group=root
  with_items:
    - "etc/skel/.zshrc"
    - "etc/default/useradd"
    - "usr/local/share/zsh/site-functions/prompt_wunjo_setup"
    - "usr/local/share/zsh/site-functions/zgitinit"
    - "etc/DIR_COLORS.256"

- copy: src={{ item }} dest=/etc/zsh/ owner=root group=root
  with_fileglob:
    - etc/zsh/*
