- name: Create user root
  user: name=root home=/root state=present

- name: Ensure directory .ssh exists
  file: name=/root/.ssh owner=root group=root mode=700 state=directory

- name: Copy autorized keys
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=600